global using System.ComponentModel.DataAnnotations;
global using ASP_Core_Middlewares.Models;
global using Microsoft.EntityFrameworkCore;
global using ASP_Core_Middlewares.Data;
global using ASP_Core_Middlewares.IRepository;
global using Microsoft.AspNetCore.Mvc;
global using ASP_Core_Middlewares.Middlewares;
global using ASP_Core_Middlewares.Repository;
global using ASP_Core_Middlewares.ActionFilters;